# Generated by Django 6.0 on 2026-01-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_dimensions',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='seller',
            field=models.CharField(default='Unknown Seller', max_length=100),
        ),
    ]
