# Generated by Django 6.0 on 2026-01-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productmodel_color_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft'), ('BR', 'Broken')], default='BR', max_length=2),
        ),
    ]
