# Generated by Django 6.0 on 2026-01-15 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productmodel_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ['-publish_timestamp', '-updated', '-timestamp']},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft'), ('BR', 'Broken')], default='DR', max_length=2),
        ),
    ]
